- 1.1.11
- _NAME: G604 Wireless Gaming Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert, thumb-scroll-mode, report_rate_extended, pointer_speed,
    speed-change, backlight, backlight_level, backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered, backlight-timed, fn-swap,
    reprogrammable-keys, persistent-remappable-keys, divert-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led,
    multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 0x1000
  _modelId: B02440850000
  _sensitive: {dpi: true, led_control: true, onboard_profiles: false}
  _serial: 607AECDD
  _unitId: 607AECDD
  _wpid: '4085'
  change-host: null
  dpi: 0x258
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  led_control: 0x0
  onboard_profiles: 0x1
  report_rate: 0x1
- _NAME: G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, report_rate_extended, pointer_speed, dpi, speed-change, backlight, backlight_level, backlight_duration_hands_out, backlight_duration_hands_in,
    backlight_duration_powered, backlight-timed, led_control, led_zone_, fn-swap, reprogrammable-keys, persistent-remappable-keys, disable-keyboard-keys,
    crown-smooth, divert-crown, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 0x1001
  _modelId: B354407CC33E
  _sensitive: {change-host: true, divert-gkeys: true, divert-keys: true, hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore,
    m-key-leds: true, mr-key-led: true, onboard_profiles: true, report_rate: true}
  _serial: 3A164654
  _unitId: 3A164654
  _wpid: 407C
  change-host: null
  divert-gkeys: true
  divert-keys: {0xd1: 0x1, 0xd2: 0x0}
  m-key-leds: {0x1: true, 0x2: true, 0x4: true}
  mr-key-led: true
  onboard_profiles: 0x1
  report_rate: 0x1
