#! /bin/bash
gap=10
PANEL_HEIGHT=30
BORDER_WIDTH=2
export gap
export PANEL_HEIGHT
export BORDER_WIDTH

#АВТОСТАРТ
sxhkd &
nm-applet &
numlockx &
polybar david &
setxkbmap us,ru -option 'grp:alt_shift_toggle'
picom -b &
feh --bg-scale ~/Pictures/green_sky.jpg
xsetroot -cursor_name left_ptr &
pgrep -x panel > /dev/null || panel &
#kilall btops
#btops &

#РАБОЧИЕ СТОЛЫ
bspc monitor -d 1 2 3 4 5 6

#РАМКИ И ОТСТУПЫ
bspc config border_width $BORDER_WIDTH
bspc config window_gap $gap;
bspc config normal_border_color "#063900"
bspc config active_border_color "#1bff00"
bspc config focused_border_color "#12a600"

#ЦВЕТ ПРОСТРАНСТВА ПРИ ВЫБОРЕ ПОЛОЖЕНИЯ НОВОГО ОКНА
bspc config presel_feedback_color "#7dff00"

#ПРИ ПОМОЩИ ЭТОЙ ХРЕНИ МОЖНО СДЕЛАТЬ ГАПСЫ ТОЛЬКО МЕЖДУ ОКНАМИ
#bspc config window_gap $gap;
#bspc config top_padding -$(($gap+2))
#bspc config left_padding -$(($gap+2))
#bspc config right_padding -$(($gap+4))
bspc config top_padding $(($PANEL_HEIGHT-$gap))

#КОФИЦИЕНТ РАЗДЕЛЕНИЯ, СКОЛЬКО ПРОЦЕНТОВ ОСТАНЕТСЯ ОТ РОДИТЕЛЬСКОГО ОКНА ПРИ ОТКРЫТИИ НОВОГО
bspc config split_ratio          0.5

#ФОКУС ОКНА НАВЕДЕНИЕМ КУРСОРА
bspc config focus_follows_pointer true
bspc config pointer_modifier	  super

#РЕЖИМ МОНОКЛЯ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config single_monocle	  false

#ОТКЛЮЧЕНИЕ ГАПСОВ РАМОК И ОТСТУПОВ КОГДА ОТКРЫТО ОДНО ОКНО
#bspc config borderless_monocle   false
#bspc config gapless_monocle      false
#bspc config paddingless_monocle	 true

#СХЕМЫ СОГЛАСНО КОТОРЫМ БУДУТ ОТКРЫВАТСЯ ОКНА
#bspc rule -a \* node=focused split_dir=east
#bspc config automatic_scheme	spiral

#ПРАВИЛА ОКОН
bspc rule -a Pcmanfm state=floating
bspc rule -a Galculator state=floating
